# Generated by Django 4.2.1 on 2023-05-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='images/1.jpg', upload_to='images'),
        ),
    ]
