# Generated by Django 4.2.1 on 2023-05-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to=''),
        ),
    ]
